server:
  port: 10000

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/

zuul:
  routes:
    account-service:
      path: /account/**
      stripPrefix: false
    order-service:
      path: /order/**
      stripPrefix: false